language: python
python:
- '3.6'
- '3.5'
install:
- pip3 install --upgrade pip
- pip3 install -r requirements-dev.txt
script:
- mypy --ignore-missing-imports --follow-imports=skip --strict-optional --warn-no-return
  amundsenatlastypes
deploy:
- provider: pypi
  user: verdan
  password:
    secure: JF24fydy8RfT1EoFZyf3Y7C0skGgYIhvd0knJHwbtyJIOli3kkNrRxtTevfo9omo8nzLLLrEj7pikbKyYfJCV3Qw9pRalZLLzQyy5SI2aEGY695mf+Se2rsnBOT9kzJEflRi4uGTILdtoXuinxS3GgFqR7iLfV7iy7TtpPMFl7HlBSK5u9uDhiE592JP6tIIfSvEvLhrKDQHBVYtdTy0xUW2Ndxy9Q2Z1Wqfz0Dzxgtihys0x0zh0rlfYLK6SutunGSPo7G3NluNu3SK9qAc4adtuirj7cQW3MKyQKTEOvZxFTlEi1Q7l7M5ciBP+BJYNNPn7gnEmioFrZtBNfKjL4kDI6usjba8mJEf6FXtjmio2uRba20zExt+ikT+pCP2yLX5+KcK9Y6rybkvnlh2CZCnfUkceIWEXPkhBjT+u61typ0kjI1GHphYjkeLzHcJLnqNAuiCn1O212VqHFXz/F/UXPw2LYl4AXJvHm754hCATg+49+JkTuvGG+W3fu2MvPL32RPXpbVDqe/sBJ+ee7vOloMGbFeUjLzvSuMU9lGFBrQSjovG5xjW3c0fBSHSqSqQiQyBukayn5F+7ducDFWTU438p2L3r0jL2QOEURW1S5DX//6ZSljNN98jC52zMWm+p3Ts2GaTjv49WaBOYOZ6nfMLJvzyZ4lzaXUsHhU=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  server:
  on:
    tags: true
    repo: dwarszawski/amundsen-atlas-types